

<!DOCTYPE html>
<!--[if IE 8]><html class="no-js lt-ie9" lang="en" > <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en" > <!--<![endif]-->
<head>
  <meta charset="utf-8">
  
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  
  <title>06 Built-in Exceptions &mdash; Python Standard Library</title>
  

  
  
    <link rel="shortcut icon" href="../_static/py.png"/>
  

  

  
  
    

  

  
  
    <link rel="stylesheet" href="../_static/css/theme.css" type="text/css" />
  

  

  
    <link rel="top" title="Python Standard Library" href="../index.html"/>
        <link rel="up" title="Ch 01 - 10" href="../01to10.html"/>
        <link rel="next" title="7. String Services" href="../07_string_services/7.html"/>
        <link rel="prev" title="13. Special Attributes" href="../05_builtin_types/special_attr.html"/> 

  
  <script src="../_static/js/modernizr.min.js"></script>

</head>

<body class="wy-body-for-nav" role="document">

   
  <div class="wy-grid-for-nav">

    
    <nav data-toggle="wy-nav-shift" class="wy-nav-side">
      <div class="wy-side-scroll">
        <div class="wy-side-nav-search">
          

          
            <a href="../index.html" class="icon icon-home"> Python Standard Library
          

          
          </a>

          
            
            
          

          
<div role="search">
  <form id="rtd-search-form" class="wy-form" action="../search.html" method="get">
    <input type="text" name="q" placeholder="Search docs" />
    <input type="hidden" name="check_keywords" value="yes" />
    <input type="hidden" name="area" value="default" />
  </form>
</div>

          
        </div>

        <div class="wy-menu wy-menu-vertical" data-spy="affix" role="navigation" aria-label="main navigation">
          
            
            
                <p class="caption"><span class="caption-text">Table of Contents</span></p>
<ul>
<li class="toctree-l1"><a class="reference internal" href="../01to10.html">Ch 01 - 10</a></li>
<li class="toctree-l1"><a class="reference internal" href="../11to20.html">Ch 11 - 20</a></li>
<li class="toctree-l1"><a class="reference internal" href="../21to30.html">Ch 21 - 30</a></li>
<li class="toctree-l1"><a class="reference internal" href="../31to37.html">Ch 31 - 37</a></li>
</ul>
<p class="caption"><span class="caption-text">Autogenerated API</span></p>
<ul>
<li class="toctree-l1"><a class="reference internal" href="../api_06to10.html">API: 06 - 10</a></li>
<li class="toctree-l1"><a class="reference internal" href="../api_11to15.html">API: 11 - 15</a></li>
<li class="toctree-l1"><a class="reference internal" href="../api_16to20.html">API: 16 - 20</a></li>
<li class="toctree-l1"><a class="reference internal" href="../api_21to25.html">API: 21 - 25</a></li>
<li class="toctree-l1"><a class="reference internal" href="../api_26to30.html">API: 26 - 30</a></li>
<li class="toctree-l1"><a class="reference internal" href="../api_31to37.html">API: 31 - 37</a></li>
</ul>

            
          
        </div>
      </div>
    </nav>

    <section data-toggle="wy-nav-shift" class="wy-nav-content-wrap">

      
      <nav class="wy-nav-top" role="navigation" aria-label="top navigation">
        
          <i data-toggle="wy-nav-top" class="fa fa-bars"></i>
          <a href="../index.html">Python Standard Library</a>
        
      </nav>


      
      <div class="wy-nav-content">
        <div class="rst-content">
          













<div role="navigation" aria-label="breadcrumbs navigation">
  <ul class="wy-breadcrumbs">
    
      <li><a href="../index.html">Docs</a> &raquo;</li>
        
          <li><a href="../01to10.html">Ch 01 - 10</a> &raquo;</li>
        
      <li>06 Built-in Exceptions</li>
    
    
      <li class="wy-breadcrumbs-aside">
        
            
            <a href="../_sources/06_exceptions/06.txt" rel="nofollow"> View page source</a>
          
        
      </li>
    
  </ul>
  <hr/>
</div>
          <div role="main" class="document" itemscope="itemscope" itemtype="http://schema.org/Article">
           <div itemprop="articleBody">
            
  <div class="section" id="module-exceptions">
<span id="built-in-exceptions"></span><span id="bltin-exceptions"></span><h1>06 Built-in Exceptions<a class="headerlink" href="#module-exceptions" title="Permalink to this headline">¶</a></h1>
<p>Exceptions should be class objects.   The exceptions are defined in the module
<a class="reference internal" href="../generated/exceptions.html#module-exceptions" title="exceptions"><code class="xref py py-mod docutils literal"><span class="pre">exceptions</span></code></a>.  This module never needs to be imported explicitly: the
exceptions are provided in the built-in namespace as well as the
<a class="reference internal" href="../generated/exceptions.html#module-exceptions" title="exceptions"><code class="xref py py-mod docutils literal"><span class="pre">exceptions</span></code></a> module.</p>
<p id="index-0">For class exceptions, in a <code class="xref std std-keyword docutils literal"><span class="pre">try</span></code> statement with an <code class="xref std std-keyword docutils literal"><span class="pre">except</span></code>
clause that mentions a particular class, that clause also handles any exception
classes derived from that class (but not exception classes from which <em>it</em> is
derived).  Two exception classes that are not related via subclassing are never
equivalent, even if they have the same name.</p>
<p id="index-1">The built-in exceptions listed below can be generated by the interpreter or
built-in functions.  Except where mentioned, they have an &#8220;associated value&#8221;
indicating the detailed cause of the error.  This may be a string or a tuple
containing several items of information (e.g., an error code and a string
explaining the code). The associated value is the second argument to the
<code class="xref std std-keyword docutils literal"><span class="pre">raise</span></code> statement.  If the exception class is derived from the standard
root class <a class="reference internal" href="../generated/exceptions.BaseException.html#exceptions.BaseException" title="exceptions.BaseException"><code class="xref py py-exc docutils literal"><span class="pre">BaseException</span></code></a>, the associated value is present as the
exception instance&#8217;s <code class="xref py py-attr docutils literal"><span class="pre">args</span></code> attribute.</p>
<p>User code can raise built-in exceptions.  This can be used to test an exception
handler or to report an error condition &#8220;just like&#8221; the situation in which the
interpreter raises the same exception; but beware that there is nothing to
prevent user code from raising an inappropriate error.</p>
<p>The built-in exception classes can be subclassed to define new exceptions;
programmers are encouraged to derive new exceptions from the <a class="reference internal" href="../generated/exceptions.Exception.html#exceptions.Exception" title="exceptions.Exception"><code class="xref py py-exc docutils literal"><span class="pre">Exception</span></code></a>
class or one of its subclasses, and not from <a class="reference internal" href="../generated/exceptions.BaseException.html#exceptions.BaseException" title="exceptions.BaseException"><code class="xref py py-exc docutils literal"><span class="pre">BaseException</span></code></a>.  More
information on defining exceptions is available in the Python Tutorial under
<span class="xref std std-ref">tut-userexceptions</span>.</p>
<p>The following exceptions are only used as base classes for other exceptions.</p>
<dl class="exception">
<dt id="exceptions.BaseException">
<em class="property">exception </em><code class="descname">BaseException</code><a class="headerlink" href="#exceptions.BaseException" title="Permalink to this definition">¶</a></dt>
<dd><p>The base class for all built-in exceptions.  It is not meant to be directly
inherited by user-defined classes (for that, use <a class="reference internal" href="../generated/exceptions.Exception.html#exceptions.Exception" title="exceptions.Exception"><code class="xref py py-exc docutils literal"><span class="pre">Exception</span></code></a>).  If
<a class="reference internal" href="../02_builtin_functions/02.html#str" title="str"><code class="xref py py-func docutils literal"><span class="pre">str()</span></code></a> or <a class="reference internal" href="../02_builtin_functions/02.html#unicode" title="unicode"><code class="xref py py-func docutils literal"><span class="pre">unicode()</span></code></a> is called on an instance of this class, the
representation of the argument(s) to the instance are returned, or the empty
string when there were no arguments.</p>
<div class="versionadded">
<p><span class="versionmodified">New in version 2.5.</span></p>
</div>
<dl class="attribute">
<dt id="exceptions.BaseException.args">
<code class="descname">args</code><a class="headerlink" href="#exceptions.BaseException.args" title="Permalink to this definition">¶</a></dt>
<dd><p>The tuple of arguments given to the exception constructor.  Some built-in
exceptions (like <a class="reference internal" href="../generated/exceptions.IOError.html#exceptions.IOError" title="exceptions.IOError"><code class="xref py py-exc docutils literal"><span class="pre">IOError</span></code></a>) expect a certain number of arguments and
assign a special meaning to the elements of this tuple, while others are
usually called only with a single string giving an error message.</p>
</dd></dl>

</dd></dl>

<dl class="exception">
<dt id="exceptions.Exception">
<em class="property">exception </em><code class="descname">Exception</code><a class="headerlink" href="#exceptions.Exception" title="Permalink to this definition">¶</a></dt>
<dd><p>All built-in, non-system-exiting exceptions are derived from this class.  All
user-defined exceptions should also be derived from this class.</p>
<div class="versionchanged">
<p><span class="versionmodified">Changed in version 2.5: </span>Changed to inherit from <a class="reference internal" href="../generated/exceptions.BaseException.html#exceptions.BaseException" title="exceptions.BaseException"><code class="xref py py-exc docutils literal"><span class="pre">BaseException</span></code></a>.</p>
</div>
</dd></dl>

<dl class="exception">
<dt id="exceptions.StandardError">
<em class="property">exception </em><code class="descname">StandardError</code><a class="headerlink" href="#exceptions.StandardError" title="Permalink to this definition">¶</a></dt>
<dd><p>The base class for all built-in exceptions except <a class="reference internal" href="../generated/exceptions.StopIteration.html#exceptions.StopIteration" title="exceptions.StopIteration"><code class="xref py py-exc docutils literal"><span class="pre">StopIteration</span></code></a>,
<a class="reference internal" href="../generated/exceptions.GeneratorExit.html#exceptions.GeneratorExit" title="exceptions.GeneratorExit"><code class="xref py py-exc docutils literal"><span class="pre">GeneratorExit</span></code></a>, <a class="reference internal" href="../generated/exceptions.KeyboardInterrupt.html#exceptions.KeyboardInterrupt" title="exceptions.KeyboardInterrupt"><code class="xref py py-exc docutils literal"><span class="pre">KeyboardInterrupt</span></code></a> and <a class="reference internal" href="../generated/exceptions.SystemExit.html#exceptions.SystemExit" title="exceptions.SystemExit"><code class="xref py py-exc docutils literal"><span class="pre">SystemExit</span></code></a>.
<a class="reference internal" href="../generated/exceptions.StandardError.html#exceptions.StandardError" title="exceptions.StandardError"><code class="xref py py-exc docutils literal"><span class="pre">StandardError</span></code></a> itself is derived from <a class="reference internal" href="../generated/exceptions.Exception.html#exceptions.Exception" title="exceptions.Exception"><code class="xref py py-exc docutils literal"><span class="pre">Exception</span></code></a>.</p>
</dd></dl>

<dl class="exception">
<dt id="exceptions.ArithmeticError">
<em class="property">exception </em><code class="descname">ArithmeticError</code><a class="headerlink" href="#exceptions.ArithmeticError" title="Permalink to this definition">¶</a></dt>
<dd><p>The base class for those built-in exceptions that are raised for various
arithmetic errors: <a class="reference internal" href="../generated/exceptions.OverflowError.html#exceptions.OverflowError" title="exceptions.OverflowError"><code class="xref py py-exc docutils literal"><span class="pre">OverflowError</span></code></a>, <a class="reference internal" href="../generated/exceptions.ZeroDivisionError.html#exceptions.ZeroDivisionError" title="exceptions.ZeroDivisionError"><code class="xref py py-exc docutils literal"><span class="pre">ZeroDivisionError</span></code></a>,
<a class="reference internal" href="../generated/exceptions.FloatingPointError.html#exceptions.FloatingPointError" title="exceptions.FloatingPointError"><code class="xref py py-exc docutils literal"><span class="pre">FloatingPointError</span></code></a>.</p>
</dd></dl>

<dl class="exception">
<dt id="exceptions.BufferError">
<em class="property">exception </em><code class="descname">BufferError</code><a class="headerlink" href="#exceptions.BufferError" title="Permalink to this definition">¶</a></dt>
<dd><p>Raised when a <span class="xref std std-ref">buffer</span> related operation cannot be
performed.</p>
</dd></dl>

<dl class="exception">
<dt id="exceptions.LookupError">
<em class="property">exception </em><code class="descname">LookupError</code><a class="headerlink" href="#exceptions.LookupError" title="Permalink to this definition">¶</a></dt>
<dd><p>The base class for the exceptions that are raised when a key or index used on
a mapping or sequence is invalid: <a class="reference internal" href="../generated/exceptions.IndexError.html#exceptions.IndexError" title="exceptions.IndexError"><code class="xref py py-exc docutils literal"><span class="pre">IndexError</span></code></a>, <a class="reference internal" href="../generated/exceptions.KeyError.html#exceptions.KeyError" title="exceptions.KeyError"><code class="xref py py-exc docutils literal"><span class="pre">KeyError</span></code></a>.  This
can be raised directly by <a class="reference internal" href="../generated/codecs.lookup.html#codecs.lookup" title="codecs.lookup"><code class="xref py py-func docutils literal"><span class="pre">codecs.lookup()</span></code></a>.</p>
</dd></dl>

<dl class="exception">
<dt id="exceptions.EnvironmentError">
<em class="property">exception </em><code class="descname">EnvironmentError</code><a class="headerlink" href="#exceptions.EnvironmentError" title="Permalink to this definition">¶</a></dt>
<dd><p>The base class for exceptions that can occur outside the Python system:
<a class="reference internal" href="../generated/exceptions.IOError.html#exceptions.IOError" title="exceptions.IOError"><code class="xref py py-exc docutils literal"><span class="pre">IOError</span></code></a>, <a class="reference internal" href="../generated/exceptions.OSError.html#exceptions.OSError" title="exceptions.OSError"><code class="xref py py-exc docutils literal"><span class="pre">OSError</span></code></a>.  When exceptions of this type are created with a
2-tuple, the first item is available on the instance&#8217;s <a class="reference internal" href="../generated/errno.html#module-errno" title="errno"><code class="xref py py-attr docutils literal"><span class="pre">errno</span></code></a> attribute
(it is assumed to be an error number), and the second item is available on the
<code class="xref py py-attr docutils literal"><span class="pre">strerror</span></code> attribute (it is usually the associated error message).  The
tuple itself is also available on the <code class="xref py py-attr docutils literal"><span class="pre">args</span></code> attribute.</p>
<div class="versionadded">
<p><span class="versionmodified">New in version 1.5.2.</span></p>
</div>
<p>When an <a class="reference internal" href="../generated/exceptions.EnvironmentError.html#exceptions.EnvironmentError" title="exceptions.EnvironmentError"><code class="xref py py-exc docutils literal"><span class="pre">EnvironmentError</span></code></a> exception is instantiated with a 3-tuple, the
first two items are available as above, while the third item is available on the
<code class="xref py py-attr docutils literal"><span class="pre">filename</span></code> attribute.  However, for backwards compatibility, the
<code class="xref py py-attr docutils literal"><span class="pre">args</span></code> attribute contains only a 2-tuple of the first two constructor
arguments.</p>
<p>The <code class="xref py py-attr docutils literal"><span class="pre">filename</span></code> attribute is <code class="docutils literal"><span class="pre">None</span></code> when this exception is created with
other than 3 arguments.  The <a class="reference internal" href="../generated/errno.html#module-errno" title="errno"><code class="xref py py-attr docutils literal"><span class="pre">errno</span></code></a> and <code class="xref py py-attr docutils literal"><span class="pre">strerror</span></code> attributes are
also <code class="docutils literal"><span class="pre">None</span></code> when the instance was created with other than 2 or 3 arguments.
In this last case, <code class="xref py py-attr docutils literal"><span class="pre">args</span></code> contains the verbatim constructor arguments as a
tuple.</p>
</dd></dl>

<p>The following exceptions are the exceptions that are actually raised.</p>
<dl class="exception">
<dt id="exceptions.AssertionError">
<em class="property">exception </em><code class="descname">AssertionError</code><a class="headerlink" href="#exceptions.AssertionError" title="Permalink to this definition">¶</a></dt>
<dd><span class="target" id="index-2"></span></dd></dl>

<dl class="exception">
<dt id="exceptions.AttributeError">
<em class="property">exception </em><code class="descname">AttributeError</code><a class="headerlink" href="#exceptions.AttributeError" title="Permalink to this definition">¶</a></dt>
<dd><p>Raised when an attribute reference (see <span class="xref std std-ref">attribute-references</span>) or
assignment fails.  (When an object does not support attribute references or
attribute assignments at all, <a class="reference internal" href="../generated/exceptions.TypeError.html#exceptions.TypeError" title="exceptions.TypeError"><code class="xref py py-exc docutils literal"><span class="pre">TypeError</span></code></a> is raised.)</p>
</dd></dl>

<dl class="exception">
<dt id="exceptions.EOFError">
<em class="property">exception </em><code class="descname">EOFError</code><a class="headerlink" href="#exceptions.EOFError" title="Permalink to this definition">¶</a></dt>
<dd><p>Raised when one of the built-in functions (<a class="reference internal" href="../02_builtin_functions/02.html#input" title="input"><code class="xref py py-func docutils literal"><span class="pre">input()</span></code></a> or <a class="reference internal" href="../02_builtin_functions/02.html#raw_input" title="raw_input"><code class="xref py py-func docutils literal"><span class="pre">raw_input()</span></code></a>)
hits an end-of-file condition (EOF) without reading any data. (N.B.: the
<a class="reference internal" href="../05_builtin_types/file_objects.html#file.read" title="file.read"><code class="xref py py-meth docutils literal"><span class="pre">file.read()</span></code></a> and <a class="reference internal" href="../05_builtin_types/file_objects.html#file.readline" title="file.readline"><code class="xref py py-meth docutils literal"><span class="pre">file.readline()</span></code></a> methods return an empty string
when they hit EOF.)</p>
</dd></dl>

<dl class="exception">
<dt id="exceptions.FloatingPointError">
<em class="property">exception </em><code class="descname">FloatingPointError</code><a class="headerlink" href="#exceptions.FloatingPointError" title="Permalink to this definition">¶</a></dt>
<dd><p>Raised when a floating point operation fails.  This exception is always defined,
but can only be raised when Python is configured with the
<code class="docutils literal"><span class="pre">--with-fpectl</span></code> option, or the <code class="xref py py-const docutils literal"><span class="pre">WANT_SIGFPE_HANDLER</span></code> symbol is
defined in the <code class="file docutils literal"><span class="pre">pyconfig.h</span></code> file.</p>
</dd></dl>

<dl class="exception">
<dt id="exceptions.GeneratorExit">
<em class="property">exception </em><code class="descname">GeneratorExit</code><a class="headerlink" href="#exceptions.GeneratorExit" title="Permalink to this definition">¶</a></dt>
<dd><p>Raised when a <span class="xref std std-term">generator</span>&#8216;s <code class="xref py py-meth docutils literal"><span class="pre">close()</span></code> method is called.  It
directly inherits from <a class="reference internal" href="../generated/exceptions.BaseException.html#exceptions.BaseException" title="exceptions.BaseException"><code class="xref py py-exc docutils literal"><span class="pre">BaseException</span></code></a> instead of <a class="reference internal" href="../generated/exceptions.StandardError.html#exceptions.StandardError" title="exceptions.StandardError"><code class="xref py py-exc docutils literal"><span class="pre">StandardError</span></code></a>
since it is technically not an error.</p>
<div class="versionadded">
<p><span class="versionmodified">New in version 2.5.</span></p>
</div>
<div class="versionchanged">
<p><span class="versionmodified">Changed in version 2.6: </span>Changed to inherit from <a class="reference internal" href="../generated/exceptions.BaseException.html#exceptions.BaseException" title="exceptions.BaseException"><code class="xref py py-exc docutils literal"><span class="pre">BaseException</span></code></a>.</p>
</div>
</dd></dl>

<dl class="exception">
<dt id="exceptions.IOError">
<em class="property">exception </em><code class="descname">IOError</code><a class="headerlink" href="#exceptions.IOError" title="Permalink to this definition">¶</a></dt>
<dd><p>Raised when an I/O operation (such as a <code class="xref std std-keyword docutils literal"><span class="pre">print</span></code> statement, the built-in
<a class="reference internal" href="../02_builtin_functions/02.html#open" title="open"><code class="xref py py-func docutils literal"><span class="pre">open()</span></code></a> function or a method of a file object) fails for an I/O-related
reason, e.g., &#8220;file not found&#8221; or &#8220;disk full&#8221;.</p>
<p>This class is derived from <a class="reference internal" href="../generated/exceptions.EnvironmentError.html#exceptions.EnvironmentError" title="exceptions.EnvironmentError"><code class="xref py py-exc docutils literal"><span class="pre">EnvironmentError</span></code></a>.  See the discussion above
for more information on exception instance attributes.</p>
<div class="versionchanged">
<p><span class="versionmodified">Changed in version 2.6: </span>Changed <a class="reference internal" href="../generated/socket.error.html#socket.error" title="socket.error"><code class="xref py py-exc docutils literal"><span class="pre">socket.error</span></code></a> to use this as a base class.</p>
</div>
</dd></dl>

<dl class="exception">
<dt id="exceptions.ImportError">
<em class="property">exception </em><code class="descname">ImportError</code><a class="headerlink" href="#exceptions.ImportError" title="Permalink to this definition">¶</a></dt>
<dd><p>Raised when an <code class="xref std std-keyword docutils literal"><span class="pre">import</span></code> statement fails to find the module definition
or when a <code class="docutils literal"><span class="pre">from</span> <span class="pre">...</span> <span class="pre">import</span></code> fails to find a name that is to be imported.</p>
</dd></dl>

<dl class="exception">
<dt id="exceptions.IndexError">
<em class="property">exception </em><code class="descname">IndexError</code><a class="headerlink" href="#exceptions.IndexError" title="Permalink to this definition">¶</a></dt>
<dd><p>Raised when a sequence subscript is out of range.  (Slice indices are silently
truncated to fall in the allowed range; if an index is not a plain integer,
<a class="reference internal" href="../generated/exceptions.TypeError.html#exceptions.TypeError" title="exceptions.TypeError"><code class="xref py py-exc docutils literal"><span class="pre">TypeError</span></code></a> is raised.)</p>
</dd></dl>

<dl class="exception">
<dt id="exceptions.KeyError">
<em class="property">exception </em><code class="descname">KeyError</code><a class="headerlink" href="#exceptions.KeyError" title="Permalink to this definition">¶</a></dt>
<dd><p>Raised when a mapping (dictionary) key is not found in the set of existing keys.</p>
</dd></dl>

<dl class="exception">
<dt id="exceptions.KeyboardInterrupt">
<em class="property">exception </em><code class="descname">KeyboardInterrupt</code><a class="headerlink" href="#exceptions.KeyboardInterrupt" title="Permalink to this definition">¶</a></dt>
<dd><p>Raised when the user hits the interrupt key (normally <code class="kbd docutils literal"><span class="pre">Control-C</span></code> or
<code class="kbd docutils literal"><span class="pre">Delete</span></code>).  During execution, a check for interrupts is made regularly.
Interrupts typed when a built-in function <a class="reference internal" href="../02_builtin_functions/02.html#input" title="input"><code class="xref py py-func docutils literal"><span class="pre">input()</span></code></a> or <a class="reference internal" href="../02_builtin_functions/02.html#raw_input" title="raw_input"><code class="xref py py-func docutils literal"><span class="pre">raw_input()</span></code></a> is
waiting for input also raise this exception. The exception inherits from
<a class="reference internal" href="../generated/exceptions.BaseException.html#exceptions.BaseException" title="exceptions.BaseException"><code class="xref py py-exc docutils literal"><span class="pre">BaseException</span></code></a> so as to not be accidentally caught by code that catches
<a class="reference internal" href="../generated/exceptions.Exception.html#exceptions.Exception" title="exceptions.Exception"><code class="xref py py-exc docutils literal"><span class="pre">Exception</span></code></a> and thus prevent the interpreter from exiting.</p>
<div class="versionchanged">
<p><span class="versionmodified">Changed in version 2.5: </span>Changed to inherit from <a class="reference internal" href="../generated/exceptions.BaseException.html#exceptions.BaseException" title="exceptions.BaseException"><code class="xref py py-exc docutils literal"><span class="pre">BaseException</span></code></a>.</p>
</div>
</dd></dl>

<dl class="exception">
<dt id="exceptions.MemoryError">
<em class="property">exception </em><code class="descname">MemoryError</code><a class="headerlink" href="#exceptions.MemoryError" title="Permalink to this definition">¶</a></dt>
<dd><p>Raised when an operation runs out of memory but the situation may still be
rescued (by deleting some objects).  The associated value is a string indicating
what kind of (internal) operation ran out of memory. Note that because of the
underlying memory management architecture (C&#8217;s <code class="xref c c-func docutils literal"><span class="pre">malloc()</span></code> function), the
interpreter may not always be able to completely recover from this situation; it
nevertheless raises an exception so that a stack traceback can be printed, in
case a run-away program was the cause.</p>
</dd></dl>

<dl class="exception">
<dt id="exceptions.NameError">
<em class="property">exception </em><code class="descname">NameError</code><a class="headerlink" href="#exceptions.NameError" title="Permalink to this definition">¶</a></dt>
<dd><p>Raised when a local or global name is not found.  This applies only to
unqualified names.  The associated value is an error message that includes the
name that could not be found.</p>
</dd></dl>

<dl class="exception">
<dt id="exceptions.NotImplementedError">
<em class="property">exception </em><code class="descname">NotImplementedError</code><a class="headerlink" href="#exceptions.NotImplementedError" title="Permalink to this definition">¶</a></dt>
<dd><p>This exception is derived from <a class="reference internal" href="../generated/exceptions.RuntimeError.html#exceptions.RuntimeError" title="exceptions.RuntimeError"><code class="xref py py-exc docutils literal"><span class="pre">RuntimeError</span></code></a>.  In user defined base
classes, abstract methods should raise this exception when they require derived
classes to override the method.</p>
<div class="versionadded">
<p><span class="versionmodified">New in version 1.5.2.</span></p>
</div>
</dd></dl>

<dl class="exception">
<dt id="exceptions.OSError">
<em class="property">exception </em><code class="descname">OSError</code><a class="headerlink" href="#exceptions.OSError" title="Permalink to this definition">¶</a></dt>
<dd><span class="target" id="index-3"></span></dd></dl>

<dl class="exception">
<dt id="exceptions.OverflowError">
<em class="property">exception </em><code class="descname">OverflowError</code><a class="headerlink" href="#exceptions.OverflowError" title="Permalink to this definition">¶</a></dt>
<dd><p>Raised when the result of an arithmetic operation is too large to be
represented.  This cannot occur for long integers (which would rather raise
<a class="reference internal" href="../generated/exceptions.MemoryError.html#exceptions.MemoryError" title="exceptions.MemoryError"><code class="xref py py-exc docutils literal"><span class="pre">MemoryError</span></code></a> than give up) and for most operations with plain integers,
which return a long integer instead.  Because of the lack of standardization
of floating point exception handling in C, most floating point operations
also aren&#8217;t checked.</p>
</dd></dl>

<dl class="exception">
<dt id="exceptions.ReferenceError">
<em class="property">exception </em><code class="descname">ReferenceError</code><a class="headerlink" href="#exceptions.ReferenceError" title="Permalink to this definition">¶</a></dt>
<dd><p>This exception is raised when a weak reference proxy, created by the
<a class="reference internal" href="../generated/weakref.proxy.html#weakref.proxy" title="weakref.proxy"><code class="xref py py-func docutils literal"><span class="pre">weakref.proxy()</span></code></a> function, is used to access an attribute of the referent
after it has been garbage collected. For more information on weak references,
see the <a class="reference internal" href="../generated/weakref.html#module-weakref" title="weakref"><code class="xref py py-mod docutils literal"><span class="pre">weakref</span></code></a> module.</p>
<div class="versionadded">
<p><span class="versionmodified">New in version 2.2: </span>Previously known as the <a class="reference internal" href="../generated/weakref.ReferenceError.html#weakref.ReferenceError" title="weakref.ReferenceError"><code class="xref py py-exc docutils literal"><span class="pre">weakref.ReferenceError</span></code></a> exception.</p>
</div>
</dd></dl>

<dl class="exception">
<dt id="exceptions.RuntimeError">
<em class="property">exception </em><code class="descname">RuntimeError</code><a class="headerlink" href="#exceptions.RuntimeError" title="Permalink to this definition">¶</a></dt>
<dd><p>Raised when an error is detected that doesn&#8217;t fall in any of the other
categories.  The associated value is a string indicating what precisely went
wrong.</p>
</dd></dl>

<dl class="exception">
<dt id="exceptions.StopIteration">
<em class="property">exception </em><code class="descname">StopIteration</code><a class="headerlink" href="#exceptions.StopIteration" title="Permalink to this definition">¶</a></dt>
<dd><p>Raised by an <span class="xref std std-term">iterator</span>&#8216;s <a class="reference internal" href="../05_builtin_types/iterator_types.html#iterator.next" title="iterator.next"><code class="xref py py-meth docutils literal"><span class="pre">next()</span></code></a> method to signal that
there are no further values.  This is derived from <a class="reference internal" href="../generated/exceptions.Exception.html#exceptions.Exception" title="exceptions.Exception"><code class="xref py py-exc docutils literal"><span class="pre">Exception</span></code></a> rather
than <a class="reference internal" href="../generated/exceptions.StandardError.html#exceptions.StandardError" title="exceptions.StandardError"><code class="xref py py-exc docutils literal"><span class="pre">StandardError</span></code></a>, since this is not considered an error in its
normal application.</p>
<div class="versionadded">
<p><span class="versionmodified">New in version 2.2.</span></p>
</div>
</dd></dl>

<dl class="exception">
<dt id="exceptions.SyntaxError">
<em class="property">exception </em><code class="descname">SyntaxError</code><a class="headerlink" href="#exceptions.SyntaxError" title="Permalink to this definition">¶</a></dt>
<dd><p>Raised when the parser encounters a syntax error.  This may occur in an
<code class="xref std std-keyword docutils literal"><span class="pre">import</span></code> statement, in an <code class="xref std std-keyword docutils literal"><span class="pre">exec</span></code> statement, in a call to the
built-in function <a class="reference internal" href="../02_builtin_functions/02.html#eval" title="eval"><code class="xref py py-func docutils literal"><span class="pre">eval()</span></code></a> or <a class="reference internal" href="../02_builtin_functions/02.html#input" title="input"><code class="xref py py-func docutils literal"><span class="pre">input()</span></code></a>, or when reading the initial
script or standard input (also interactively).</p>
<p>Instances of this class have attributes <code class="xref py py-attr docutils literal"><span class="pre">filename</span></code>, <code class="xref py py-attr docutils literal"><span class="pre">lineno</span></code>,
<code class="xref py py-attr docutils literal"><span class="pre">offset</span></code> and <code class="xref py py-attr docutils literal"><span class="pre">text</span></code> for easier access to the details.  <a class="reference internal" href="../02_builtin_functions/02.html#str" title="str"><code class="xref py py-func docutils literal"><span class="pre">str()</span></code></a>
of the exception instance returns only the message.</p>
</dd></dl>

<dl class="exception">
<dt id="exceptions.IndentationError">
<em class="property">exception </em><code class="descname">IndentationError</code><a class="headerlink" href="#exceptions.IndentationError" title="Permalink to this definition">¶</a></dt>
<dd><p>Base class for syntax errors related to incorrect indentation.  This is a
subclass of <a class="reference internal" href="../generated/exceptions.SyntaxError.html#exceptions.SyntaxError" title="exceptions.SyntaxError"><code class="xref py py-exc docutils literal"><span class="pre">SyntaxError</span></code></a>.</p>
</dd></dl>

<dl class="exception">
<dt id="exceptions.TabError">
<em class="property">exception </em><code class="descname">TabError</code><a class="headerlink" href="#exceptions.TabError" title="Permalink to this definition">¶</a></dt>
<dd><p>Raised when indentation contains an inconsistent use of tabs and spaces.
This is a subclass of <a class="reference internal" href="../generated/exceptions.IndentationError.html#exceptions.IndentationError" title="exceptions.IndentationError"><code class="xref py py-exc docutils literal"><span class="pre">IndentationError</span></code></a>.</p>
</dd></dl>

<dl class="exception">
<dt id="exceptions.SystemError">
<em class="property">exception </em><code class="descname">SystemError</code><a class="headerlink" href="#exceptions.SystemError" title="Permalink to this definition">¶</a></dt>
<dd><p>Raised when the interpreter finds an internal error, but the situation does not
look so serious to cause it to abandon all hope. The associated value is a
string indicating what went wrong (in low-level terms).</p>
<p>You should report this to the author or maintainer of your Python interpreter.
Be sure to report the version of the Python interpreter (<code class="docutils literal"><span class="pre">sys.version</span></code>; it is
also printed at the start of an interactive Python session), the exact error
message (the exception&#8217;s associated value) and if possible the source of the
program that triggered the error.</p>
</dd></dl>

<dl class="exception">
<dt id="exceptions.SystemExit">
<em class="property">exception </em><code class="descname">SystemExit</code><a class="headerlink" href="#exceptions.SystemExit" title="Permalink to this definition">¶</a></dt>
<dd><p>This exception is raised by the <a class="reference internal" href="../generated/sys.exit.html#sys.exit" title="sys.exit"><code class="xref py py-func docutils literal"><span class="pre">sys.exit()</span></code></a> function.  When it is not
handled, the Python interpreter exits; no stack traceback is printed.  If the
associated value is a plain integer, it specifies the system exit status (passed
to C&#8217;s <code class="xref c c-func docutils literal"><span class="pre">exit()</span></code> function); if it is <code class="docutils literal"><span class="pre">None</span></code>, the exit status is zero; if
it has another type (such as a string), the object&#8217;s value is printed and the
exit status is one.</p>
<p>Instances have an attribute <code class="xref py py-attr docutils literal"><span class="pre">code</span></code> which is set to the proposed exit
status or error message (defaulting to <code class="docutils literal"><span class="pre">None</span></code>). Also, this exception derives
directly from <a class="reference internal" href="../generated/exceptions.BaseException.html#exceptions.BaseException" title="exceptions.BaseException"><code class="xref py py-exc docutils literal"><span class="pre">BaseException</span></code></a> and not <a class="reference internal" href="../generated/exceptions.StandardError.html#exceptions.StandardError" title="exceptions.StandardError"><code class="xref py py-exc docutils literal"><span class="pre">StandardError</span></code></a>, since it is not
technically an error.</p>
<p>A call to <a class="reference internal" href="../generated/sys.exit.html#sys.exit" title="sys.exit"><code class="xref py py-func docutils literal"><span class="pre">sys.exit()</span></code></a> is translated into an exception so that clean-up
handlers (<code class="xref std std-keyword docutils literal"><span class="pre">finally</span></code> clauses of <code class="xref std std-keyword docutils literal"><span class="pre">try</span></code> statements) can be
executed, and so that a debugger can execute a script without running the risk
of losing control.  The <a class="reference internal" href="../15_allos/os.html#os._exit" title="os._exit"><code class="xref py py-func docutils literal"><span class="pre">os._exit()</span></code></a> function can be used if it is
absolutely positively necessary to exit immediately (for example, in the child
process after a call to <a class="reference internal" href="../generated/os.fork.html#os.fork" title="os.fork"><code class="xref py py-func docutils literal"><span class="pre">os.fork()</span></code></a>).</p>
<p>The exception inherits from <a class="reference internal" href="../generated/exceptions.BaseException.html#exceptions.BaseException" title="exceptions.BaseException"><code class="xref py py-exc docutils literal"><span class="pre">BaseException</span></code></a> instead of <a class="reference internal" href="../generated/exceptions.StandardError.html#exceptions.StandardError" title="exceptions.StandardError"><code class="xref py py-exc docutils literal"><span class="pre">StandardError</span></code></a>
or <a class="reference internal" href="../generated/exceptions.Exception.html#exceptions.Exception" title="exceptions.Exception"><code class="xref py py-exc docutils literal"><span class="pre">Exception</span></code></a> so that it is not accidentally caught by code that catches
<a class="reference internal" href="../generated/exceptions.Exception.html#exceptions.Exception" title="exceptions.Exception"><code class="xref py py-exc docutils literal"><span class="pre">Exception</span></code></a>.  This allows the exception to properly propagate up and cause
the interpreter to exit.</p>
<div class="versionchanged">
<p><span class="versionmodified">Changed in version 2.5: </span>Changed to inherit from <a class="reference internal" href="../generated/exceptions.BaseException.html#exceptions.BaseException" title="exceptions.BaseException"><code class="xref py py-exc docutils literal"><span class="pre">BaseException</span></code></a>.</p>
</div>
</dd></dl>

<dl class="exception">
<dt id="exceptions.TypeError">
<em class="property">exception </em><code class="descname">TypeError</code><a class="headerlink" href="#exceptions.TypeError" title="Permalink to this definition">¶</a></dt>
<dd><p>Raised when an operation or function is applied to an object of inappropriate
type.  The associated value is a string giving details about the type mismatch.</p>
</dd></dl>

<dl class="exception">
<dt id="exceptions.UnboundLocalError">
<em class="property">exception </em><code class="descname">UnboundLocalError</code><a class="headerlink" href="#exceptions.UnboundLocalError" title="Permalink to this definition">¶</a></dt>
<dd><p>Raised when a reference is made to a local variable in a function or method, but
no value has been bound to that variable.  This is a subclass of
<a class="reference internal" href="../generated/exceptions.NameError.html#exceptions.NameError" title="exceptions.NameError"><code class="xref py py-exc docutils literal"><span class="pre">NameError</span></code></a>.</p>
<div class="versionadded">
<p><span class="versionmodified">New in version 2.0.</span></p>
</div>
</dd></dl>

<dl class="exception">
<dt id="exceptions.UnicodeError">
<em class="property">exception </em><code class="descname">UnicodeError</code><a class="headerlink" href="#exceptions.UnicodeError" title="Permalink to this definition">¶</a></dt>
<dd><p>Raised when a Unicode-related encoding or decoding error occurs.  It is a
subclass of <a class="reference internal" href="../generated/exceptions.ValueError.html#exceptions.ValueError" title="exceptions.ValueError"><code class="xref py py-exc docutils literal"><span class="pre">ValueError</span></code></a>.</p>
<p><a class="reference internal" href="../generated/exceptions.UnicodeError.html#exceptions.UnicodeError" title="exceptions.UnicodeError"><code class="xref py py-exc docutils literal"><span class="pre">UnicodeError</span></code></a> has attributes that describe the encoding or decoding
error.  For example, <code class="docutils literal"><span class="pre">err.object[err.start:err.end]</span></code> gives the particular
invalid input that the codec failed on.</p>
<dl class="attribute">
<dt id="exceptions.UnicodeError.encoding">
<code class="descname">encoding</code><a class="headerlink" href="#exceptions.UnicodeError.encoding" title="Permalink to this definition">¶</a></dt>
<dd><p>The name of the encoding that raised the error.</p>
</dd></dl>

<dl class="attribute">
<dt id="exceptions.UnicodeError.reason">
<code class="descname">reason</code><a class="headerlink" href="#exceptions.UnicodeError.reason" title="Permalink to this definition">¶</a></dt>
<dd><p>A string describing the specific codec error.</p>
</dd></dl>

<dl class="attribute">
<dt id="exceptions.UnicodeError.object">
<code class="descname">object</code><a class="headerlink" href="#exceptions.UnicodeError.object" title="Permalink to this definition">¶</a></dt>
<dd><p>The object the codec was attempting to encode or decode.</p>
</dd></dl>

<dl class="attribute">
<dt id="exceptions.UnicodeError.start">
<code class="descname">start</code><a class="headerlink" href="#exceptions.UnicodeError.start" title="Permalink to this definition">¶</a></dt>
<dd><p>The first index of invalid data in <a class="reference internal" href="../02_builtin_functions/02.html#object" title="object"><code class="xref py py-attr docutils literal"><span class="pre">object</span></code></a>.</p>
</dd></dl>

<dl class="attribute">
<dt id="exceptions.UnicodeError.end">
<code class="descname">end</code><a class="headerlink" href="#exceptions.UnicodeError.end" title="Permalink to this definition">¶</a></dt>
<dd><p>The index after the last invalid data in <a class="reference internal" href="../02_builtin_functions/02.html#object" title="object"><code class="xref py py-attr docutils literal"><span class="pre">object</span></code></a>.</p>
</dd></dl>

<div class="versionadded">
<p><span class="versionmodified">New in version 2.0.</span></p>
</div>
</dd></dl>

<dl class="exception">
<dt id="exceptions.UnicodeEncodeError">
<em class="property">exception </em><code class="descname">UnicodeEncodeError</code><a class="headerlink" href="#exceptions.UnicodeEncodeError" title="Permalink to this definition">¶</a></dt>
<dd><p>Raised when a Unicode-related error occurs during encoding.  It is a subclass of
<a class="reference internal" href="../generated/exceptions.UnicodeError.html#exceptions.UnicodeError" title="exceptions.UnicodeError"><code class="xref py py-exc docutils literal"><span class="pre">UnicodeError</span></code></a>.</p>
<div class="versionadded">
<p><span class="versionmodified">New in version 2.3.</span></p>
</div>
</dd></dl>

<dl class="exception">
<dt id="exceptions.UnicodeDecodeError">
<em class="property">exception </em><code class="descname">UnicodeDecodeError</code><a class="headerlink" href="#exceptions.UnicodeDecodeError" title="Permalink to this definition">¶</a></dt>
<dd><p>Raised when a Unicode-related error occurs during decoding.  It is a subclass of
<a class="reference internal" href="../generated/exceptions.UnicodeError.html#exceptions.UnicodeError" title="exceptions.UnicodeError"><code class="xref py py-exc docutils literal"><span class="pre">UnicodeError</span></code></a>.</p>
<div class="versionadded">
<p><span class="versionmodified">New in version 2.3.</span></p>
</div>
</dd></dl>

<dl class="exception">
<dt id="exceptions.UnicodeTranslateError">
<em class="property">exception </em><code class="descname">UnicodeTranslateError</code><a class="headerlink" href="#exceptions.UnicodeTranslateError" title="Permalink to this definition">¶</a></dt>
<dd><p>Raised when a Unicode-related error occurs during translating.  It is a subclass
of <a class="reference internal" href="../generated/exceptions.UnicodeError.html#exceptions.UnicodeError" title="exceptions.UnicodeError"><code class="xref py py-exc docutils literal"><span class="pre">UnicodeError</span></code></a>.</p>
<div class="versionadded">
<p><span class="versionmodified">New in version 2.3.</span></p>
</div>
</dd></dl>

<dl class="exception">
<dt id="exceptions.ValueError">
<em class="property">exception </em><code class="descname">ValueError</code><a class="headerlink" href="#exceptions.ValueError" title="Permalink to this definition">¶</a></dt>
<dd><p>Raised when a built-in operation or function receives an argument that has the
right type but an inappropriate value, and the situation is not described by a
more precise exception such as <a class="reference internal" href="../generated/exceptions.IndexError.html#exceptions.IndexError" title="exceptions.IndexError"><code class="xref py py-exc docutils literal"><span class="pre">IndexError</span></code></a>.</p>
</dd></dl>

<dl class="exception">
<dt id="exceptions.VMSError">
<em class="property">exception </em><code class="descname">VMSError</code><a class="headerlink" href="#exceptions.VMSError" title="Permalink to this definition">¶</a></dt>
<dd><p>Only available on VMS.  Raised when a VMS-specific error occurs.</p>
</dd></dl>

<dl class="exception">
<dt id="exceptions.WindowsError">
<em class="property">exception </em><code class="descname">WindowsError</code><a class="headerlink" href="#exceptions.WindowsError" title="Permalink to this definition">¶</a></dt>
<dd><p>Raised when a Windows-specific error occurs or when the error number does not
correspond to an <code class="xref c c-data docutils literal"><span class="pre">errno</span></code> value.  The <code class="xref py py-attr docutils literal"><span class="pre">winerror</span></code> and
<code class="xref py py-attr docutils literal"><span class="pre">strerror</span></code> values are created from the return values of the
<code class="xref c c-func docutils literal"><span class="pre">GetLastError()</span></code> and <code class="xref c c-func docutils literal"><span class="pre">FormatMessage()</span></code> functions from the Windows
Platform API. The <a class="reference internal" href="../generated/errno.html#module-errno" title="errno"><code class="xref py py-attr docutils literal"><span class="pre">errno</span></code></a> value maps the <code class="xref py py-attr docutils literal"><span class="pre">winerror</span></code> value to
corresponding <code class="docutils literal"><span class="pre">errno.h</span></code> values. This is a subclass of <a class="reference internal" href="../generated/exceptions.OSError.html#exceptions.OSError" title="exceptions.OSError"><code class="xref py py-exc docutils literal"><span class="pre">OSError</span></code></a>.</p>
<div class="versionadded">
<p><span class="versionmodified">New in version 2.0.</span></p>
</div>
<div class="versionchanged">
<p><span class="versionmodified">Changed in version 2.5: </span>Previous versions put the <code class="xref c c-func docutils literal"><span class="pre">GetLastError()</span></code> codes into <a class="reference internal" href="../generated/errno.html#module-errno" title="errno"><code class="xref py py-attr docutils literal"><span class="pre">errno</span></code></a>.</p>
</div>
</dd></dl>

<dl class="exception">
<dt id="exceptions.ZeroDivisionError">
<em class="property">exception </em><code class="descname">ZeroDivisionError</code><a class="headerlink" href="#exceptions.ZeroDivisionError" title="Permalink to this definition">¶</a></dt>
<dd><p>Raised when the second argument of a division or modulo operation is zero.  The
associated value is a string indicating the type of the operands and the
operation.</p>
</dd></dl>

<p>The following exceptions are used as warning categories; see the <a class="reference internal" href="../generated/warnings.html#module-warnings" title="warnings"><code class="xref py py-mod docutils literal"><span class="pre">warnings</span></code></a>
module for more information.</p>
<dl class="exception">
<dt id="exceptions.Warning">
<em class="property">exception </em><code class="descname">Warning</code><a class="headerlink" href="#exceptions.Warning" title="Permalink to this definition">¶</a></dt>
<dd><p>Base class for warning categories.</p>
</dd></dl>

<dl class="exception">
<dt id="exceptions.UserWarning">
<em class="property">exception </em><code class="descname">UserWarning</code><a class="headerlink" href="#exceptions.UserWarning" title="Permalink to this definition">¶</a></dt>
<dd><p>Base class for warnings generated by user code.</p>
</dd></dl>

<dl class="exception">
<dt id="exceptions.DeprecationWarning">
<em class="property">exception </em><code class="descname">DeprecationWarning</code><a class="headerlink" href="#exceptions.DeprecationWarning" title="Permalink to this definition">¶</a></dt>
<dd><p>Base class for warnings about deprecated features.</p>
</dd></dl>

<dl class="exception">
<dt id="exceptions.PendingDeprecationWarning">
<em class="property">exception </em><code class="descname">PendingDeprecationWarning</code><a class="headerlink" href="#exceptions.PendingDeprecationWarning" title="Permalink to this definition">¶</a></dt>
<dd><p>Base class for warnings about features which will be deprecated in the future.</p>
</dd></dl>

<dl class="exception">
<dt id="exceptions.SyntaxWarning">
<em class="property">exception </em><code class="descname">SyntaxWarning</code><a class="headerlink" href="#exceptions.SyntaxWarning" title="Permalink to this definition">¶</a></dt>
<dd><p>Base class for warnings about dubious syntax.</p>
</dd></dl>

<dl class="exception">
<dt id="exceptions.RuntimeWarning">
<em class="property">exception </em><code class="descname">RuntimeWarning</code><a class="headerlink" href="#exceptions.RuntimeWarning" title="Permalink to this definition">¶</a></dt>
<dd><p>Base class for warnings about dubious runtime behavior.</p>
</dd></dl>

<dl class="exception">
<dt id="exceptions.FutureWarning">
<em class="property">exception </em><code class="descname">FutureWarning</code><a class="headerlink" href="#exceptions.FutureWarning" title="Permalink to this definition">¶</a></dt>
<dd><p>Base class for warnings about constructs that will change semantically in the
future.</p>
</dd></dl>

<dl class="exception">
<dt id="exceptions.ImportWarning">
<em class="property">exception </em><code class="descname">ImportWarning</code><a class="headerlink" href="#exceptions.ImportWarning" title="Permalink to this definition">¶</a></dt>
<dd><p>Base class for warnings about probable mistakes in module imports.</p>
<div class="versionadded">
<p><span class="versionmodified">New in version 2.5.</span></p>
</div>
</dd></dl>

<dl class="exception">
<dt id="exceptions.UnicodeWarning">
<em class="property">exception </em><code class="descname">UnicodeWarning</code><a class="headerlink" href="#exceptions.UnicodeWarning" title="Permalink to this definition">¶</a></dt>
<dd><p>Base class for warnings related to Unicode.</p>
<div class="versionadded">
<p><span class="versionmodified">New in version 2.5.</span></p>
</div>
</dd></dl>

<div class="section" id="exception-hierarchy">
<h2>Exception hierarchy<a class="headerlink" href="#exception-hierarchy" title="Permalink to this headline">¶</a></h2>
<p>The class hierarchy for built-in exceptions is:</p>
<div class="highlight-python"><div class="highlight"><pre><span></span>BaseException
 +-- SystemExit
 +-- KeyboardInterrupt
 +-- GeneratorExit
 +-- Exception
      +-- StopIteration
      +-- StandardError
      |    +-- BufferError
      |    +-- ArithmeticError
      |    |    +-- FloatingPointError
      |    |    +-- OverflowError
      |    |    +-- ZeroDivisionError
      |    +-- AssertionError
      |    +-- AttributeError
      |    +-- EnvironmentError
      |    |    +-- IOError
      |    |    +-- OSError
      |    |         +-- WindowsError (Windows)
      |    |         +-- VMSError (VMS)
      |    +-- EOFError
      |    +-- ImportError
      |    +-- LookupError
      |    |    +-- IndexError
      |    |    +-- KeyError
      |    +-- MemoryError
      |    +-- NameError
      |    |    +-- UnboundLocalError
      |    +-- ReferenceError
      |    +-- RuntimeError
      |    |    +-- NotImplementedError
      |    +-- SyntaxError
      |    |    +-- IndentationError
      |    |         +-- TabError
      |    +-- SystemError
      |    +-- TypeError
      |    +-- ValueError
      |         +-- UnicodeError
      |              +-- UnicodeDecodeError
      |              +-- UnicodeEncodeError
      |              +-- UnicodeTranslateError
      +-- Warning
           +-- DeprecationWarning
           +-- PendingDeprecationWarning
           +-- RuntimeWarning
           +-- SyntaxWarning
           +-- UserWarning
           +-- FutureWarning
      +-- ImportWarning
      +-- UnicodeWarning
      +-- BytesWarning
</pre></div>
</div>
</div>
</div>


           </div>
          </div>
          <footer>
  
    <div class="rst-footer-buttons" role="navigation" aria-label="footer navigation">
      
        <a href="../07_string_services/7.html" class="btn btn-neutral float-right" title="7. String Services" accesskey="n">Next <span class="fa fa-arrow-circle-right"></span></a>
      
      
        <a href="../05_builtin_types/special_attr.html" class="btn btn-neutral" title="13. Special Attributes" accesskey="p"><span class="fa fa-arrow-circle-left"></span> Previous</a>
      
    </div>
  

  <hr/>

  <div role="contentinfo">
    <p>
        &copy; Copyright 2016.

    </p>
  </div>
  Built with <a href="http://sphinx-doc.org/">Sphinx</a> using a <a href="https://github.com/snide/sphinx_rtd_theme">theme</a> provided by <a href="https://readthedocs.org">Read the Docs</a>. 

</footer>

        </div>
      </div>

    </section>

  </div>
  


  

    <script type="text/javascript">
        var DOCUMENTATION_OPTIONS = {
            URL_ROOT:'../',
            VERSION:'',
            COLLAPSE_INDEX:false,
            FILE_SUFFIX:'.html',
            HAS_SOURCE:  true
        };
    </script>
      <script type="text/javascript" src="../_static/jquery.js"></script>
      <script type="text/javascript" src="../_static/underscore.js"></script>
      <script type="text/javascript" src="../_static/doctools.js"></script>
      <script type="text/javascript" src="../_static/copybutton.js"></script>
      <script type="text/javascript" src="https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML"></script>

  

  
  
    <script type="text/javascript" src="../_static/js/theme.js"></script>
  

  
  
  <script type="text/javascript">
      jQuery(function () {
          SphinxRtdTheme.StickyNav.enable();
      });
  </script>
   

</body>
</html>